#!/usr/bin/python
#
# Python program to estimate the divergence of nonlocality in
# the additive line frames on n qubits.  The frames are
# generated by applying Hadamards in all different
# directions.

# imports

import sys, os, cPickle, random

# Configuration

qubits = 4
trials = 50
stuckmax = 50
verbose = False
showtrial = 1
twostep = False
showanswer = False
# random.seed(3)

# Work

rrange = random.randrange
rchoice = random.choice
picklefile = 'nonlocal.%d.pickle' % qubits
dim = 2**qubits

flip = {'A':'B','B':'A'}

def normalize(line):
    fac = 0
    for item in line:
        if item:
            fac = item
            break
    return tuple([item/fac for item in line])

def add(v,w): return [v[n]+w[n] for n in xrange(len(v))]
def sub(v,w): return [v[n]-w[n] for n in xrange(len(v))]
def dot(v,w): return sum([v[n]*w[n] for n in xrange(len(v))])

# Start with trivial frame

def pairstodd(graph):
    newgraph = {}
    for (x,y) in graph:
        if not x in newgraph: newgraph[x] = {}
        newgraph[x][y] = graph[(x,y)]
    return newgraph

def stash(item,l,d):
    if item in d: return (d[item],False)
    n = len(l)
    if len(d) != n:
        print 'Numbering error!'; sys.exit(1)
    l.append(item)
    d[item] = n
    return (n,True)

def dicttolist(d):
    l = [None]*len(d)
    for item in d: l[d[item]] = item
    return l

def pickle(x,level=2,enc=None):
    s = cPickle.dumps(x,level)
    if enc: s = s.encode(enc)
    return s

def unpickle(s,enc=None):
    if enc: s = s.decode(enc)
    return cPickle.loads(s)

def listcount(l):
    d = {}
    for item in l:
        if item in d: d[item] += 1
        else: d[item] = 1
    return d

def dist2(graph):
    ggraph = {}
    for v1 in graph:
        ggraph[v1] = {}
        for v2 in graph[v1]:
            for v3 in graph[v2]:
                if v1 != v3: ggraph[v1][v3] = (graph[v1][v2],graph[v2][v3])
    return ggraph

def showline(l):
    return ''.join([{-1:'-',0:'0',1:'+'}[a] for a in lines[l]])
    
def foldframe(frame):
    return tuple(sorted([rlines[normalize(line)] for line in frame]))


# Here is the main computation for building the graph
if not os.path.exists(picklefile):
    # lines eventually stores all normalized lines that can be a part of a frame
    # rlines helps us store them and look them up by assigning each a numerical label
    lines = []; rlines = {}
    # similar for frames; frames are orthogonal line bases for the space of possible qubit states i.e. the span of $(\ZZ_2)^{\otimes n}$
    frames = []; rframes = {}
    # the graph we eventually build is bipartite; on one side are Alice's possible frames, on the other are Bob's,
    # and edges connect frames that differ by a single hadamard
    owns = {'A':[],'B':[]}
    # f presumably stands for frames, this eventually holds the bipartite graph described above
    fgraph = {}

    # Build up one valid frame to start off the todo list
    # This frame looks like a 2**n by 2**n identity matrix
    # Every row is stored as a line in lines and rlines
    frame = []
    for n in range(dim):
        line = [0]*dim
        line[n] = 1
        (nline,new) = stash(normalize(line),lines,rlines)
        frame.append(line)
    
    # Store this frame in frames and rframes and give it to Alice
    (nframe,new) = stash(foldframe(frame),frames,rframes)
    owns['A'].append(nframe)

    # For every vector $v \in (\Z_2)^n$ (written as an int in [1,2**n]), z2complement[v] is an array containing
    # all of the vectors in an index-2 subspace of $(\Z_2)^n$ not containing v.
    z2complement = {}
    for v in range(1,dim):
        span = [0]
        while len(span) < dim/2:
            for w in range(1,dim):
                if w in span or w^v in span: continue
                for u in list(span): span.append(w^u)
        z2complement[v] = span

    # Begin with a single item on the todo list, and process items on the todo list until there is nothing left to be done.
    todo = [frame]
    x = 'A'; y = 'B'
    while todo:
        print 'Frames to do, %s -> %s: %s' % (x,y,len(todo))
        # newtodo is a place to put the frames we need to add to the todo list for the next iteration
        newtodo = []
        for frame1 in todo:
            nframe1 = rframes[foldframe(frame1)]
            # Fix a vector $v \in (\Z_2)^n$.
            for v in range(1,dim):
                # Over all $w \in v^\perp$, set frame2[w] = frame1[w] + frame1[v^w]
                # and set                       frame2[v^w] = frame1[w] - frame1[v^w]
                # Also store the normalized sum and difference as new lines in lines, rlines
                # TODO I think this has the effect of applying a hadamard matrix, would like to think through this more
                frame2 = [None]*dim
                lgraph = {}
                for w in z2complement[v]:
                    line1 = frame1[w]; line2 = frame1[v^w]
                    nline1 = rlines[normalize(line1)]
                    nline2 = rlines[normalize(line2)]
                    line3 = add(line1,line2); line4 = sub(line1,line2)
                    frame2[w] = line3; frame2[v^w] = line4
                    nline3 = stash(normalize(line3),lines,rlines)[0]
                    nline4 = stash(normalize(line4),lines,rlines)[0]
                    # I think (?) this stores instructions for how to get from one frame to the other
                    lgraph[(nline1,nline3)] = lgraph[(nline1,nline4)] = v
                    lgraph[(nline2,nline3)] = lgraph[(nline2,nline4)] = v
                (nframe2,new) = stash(foldframe(frame2),frames,rframes)
                # this puts an edge in the frames graph with instructions for how to get from one frame to the other
                fgraph[(nframe1,nframe2)] = pairstodd(lgraph)
                # add the neighboring frames to the todo list so that we eventually spread across the entire bipartite graph
                if new:
                    owns[y].append(nframe2)
                    newtodo.append(frame2)
        (x,y) = (y,x)
        todo = newtodo
    fgraph = pairstodd(fgraph)
    print 'Pickling lines and frames...'
    open(picklefile,'w').write(
        pickle((frames,rframes,lines,rlines,owns,fgraph)))
else:
    print 'Unpickling lines and frames...'
    (frames,rframes,lines,rlines,owns,fgraph) = \
        unpickle(open(picklefile).read())

print 'Number of A frames:',len(owns['A'])
print 'Number of B frames:',len(owns['B'])
print 'Number of lines:',len(lines)

# A sanity check
if len(listcount([len(fgraph[frame]) for frame in fgraph])) > 1:
    print 'Error!  The graph of frames is not regular!'

# Extra section: Distance 2 in four qubit case

# if twostep:
#     print 'Computing double steps...'
#     lgraph = dist2(lgraph)
#     fgraph = dist2(fgraph)
#     owns['B'] = owns['A']
#     for l1 in lgraph:
#         for l2 in list(lgraph[l1]):
#             if not dot(lines[l1],lines[l2]):
#                  del lgraph[l1][l2]

print 'Frame neighbors:',len(fgraph[0])

select = {'A':{},'B':{}}
scores = {}
allscores = {}

def makescores(x,y):
    global scores, allscores 
    allscores = {}
    scores = {}
    selectx = select[x]
    selecty = select[y]
    for f1 in owns[x]:
        f1scores = dict([(l,0) for l in frames[f1]])
        for f2 in fgraph[f1]:
            for l1 in fgraph[f2][f1][selecty[f2]]:
                f1scores[l1] += 1
        allscores[f1] = f1scores
        scores[f1] = f1scores[selectx[f1]]
    return sum(scores.values())

# Optimize X rel Y
def optimize(x,y):
    total = makescores(x,y)
    for f in owns[x]:
        fscores = allscores[f]
        scores[f] = m = max(fscores.values())
        select[x][f] = rchoice([l for (l,s) in fscores.items() if s == m])
    return sum(scores.values())

summary = []
results = []
stuck = 0
if not verbose: print 'Thinking...'
for t in xrange(1,trials+1):
    select = {'A':{},'B':{}}
    for x in ['A','B']:
        for f in owns[x]:
            select[x][f] = rchoice(frames[f])
    old = makescores('A','B')
    if verbose or not t%showtrial:
        print 'Trial:',t,'      Starting score:',old
    while True:
        scorea = optimize('A','B')
        scoreb = optimize('B','A')
        if verbose:
            print 'Optimize A, score:',scorea,
            print '     Optimize B, score:',scoreb
        if scoreb == old:
            stuck += 1
        else:
            old = scoreb
            stuck = 0
        if stuck >= stuckmax:
            if verbose: print 'Stuck %d times, quitting.' % stuck
            if showanswer and scoreb >= showanswer:
                print 'Solution found:'
                for x in select:
                    for f in owns[x]:
                        print '%s: %s' % (x,showline(select[x][f]))
                print
            if verbose: print
            break
    results.append(scoreb)
    if not t%showtrial and not verbose:
        print 'Final Score:',scoreb
        sys.stdout.flush()

print
print 'Qubits:',qubits
print 'Trials:',trials
print 'Max stuck:',stuckmax
print 'Denominator:',len(owns['A'])*len(fgraph[0])
counts = listcount(results)
for s in sorted(counts): print 'Score %d: %d' % (s,counts[s])
